server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/pet_hos_db?serverTimezone=Asia/Seoul
    username : root
    password: lms*!$Ms0828
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 409b3fb04dd78999f86c8dbc4a19372a  # 카카오 REST API 키
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/oauth/kakao/callback"
            scope: profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  h2:
    console:
      enabled: true
#      path: /h2-console
      settings:
        web-allow-others: true
      path: /h2-console

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/pethospital1 # test ??? ??? ??? ??? ???? ???.
#    username: user # username? password? ??? ??? ??
#    password: user123123
#    driver-class-name: org.h2.Driver


  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 30MB
      max-file-size: 10MB
      location: C:\upload

#  application:
#    name: user-service
#  main:
#    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: 'false'

  mail:
    host: smtp.gmail.com
    port: 465
    username: kssjjh123@gmail.com
    password: slppfbclbdecyrus
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

jwt:
    secret: AAAABBBBCCCCDDDDEEEEFFFFGGGG123!@#

org:
  zerock:
    upload:
      path: C:\upload
